routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::resources([
  'composers'             =>  'ComposerController',
  'conductors'            =>  'ConductorController',
  'countries'             =>  'CountryController',
  'masterpieces'          =>  'MasterpieceController'
]);

app/Composer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Composer extends Model
{
  // fields in the table
  protected $guarded = ['id'];

  // fields in the table
  protected $fillable = ['country_id', 'fullname'];
  
  // set timestamp, allow to use
  public $timestamps=true;


  public $messages = [
    'fullname.required'   =>  'Please enter the name of the composer',
    'fullname.unique'     =>  'This composer already exists'
  ];


  public function rulesCreate()
  {
    return [
      'fullname'   =>  'required|unique:composers,fullname'
    ];
  }


  public function rulesUpdate($id)
  {
    return [
      'fullname'   =>  'required|unique:composers,fullname,'.$id
    ];
  }


  public function country() {
    return $this->belongsTo('App\Country');
  }

  public function masterpieces() {
    return $this->hasMany('App\Masterpiece');
  }

}

app/Http/Controllers/ComposerController.php
<?php

namespace App\Http\Controllers;

use App\Composer;
use App\Country;
use App\Masterpiece;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Validator;


class ComposerController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $composers = Composer::with('country')->orderBy('fullname')->get();
    // DB::enableQueryLog();
    // dd(DB::getQueryLog(Composer::orderBy('fullname')->get()));
    return view('composer/index', compact('composers'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $composer = new Composer;
    $countries = Country::orderBy('label')->get();

    return view(
      'composer/create',
      compact('composer', 'countries')
    );
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $composer = new Composer;

    $validator = Validator::make(
      $request->all(),
      $composer->rulesCreate(),
      $composer->messages
    );

    if ($validator->fails()) {
      return redirect()
          ->route('composers.create')
          ->withErrors($validator)
          ->withInput();
    }

    Composer::create($request->all());
    
    return redirect()
        ->route('composers.index')
        ->with('success','Add success!');
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\Composer  $composer
   * @return \Illuminate\Http\Response
   */
  public function show(Composer $composer)
  {
    $composer = DB::table('composers')

        ->join(
          'countries',
          'composers.country_id',
          '=',
          'countries.id'
        )

        ->select(
          'composers.id',
          'composers.fullname',
          'countries.label as country_label'
        )

        ->where('composers.id', $composer->id)
        ->first();


    $masterpieces = Masterpiece::where('composer_id', $composer->id)
        ->orderBy('name')
        ->get();


    return view(
      'composer/show',
      compact('composer', 'masterpieces')
    );
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Composer  $composer
   * @return \Illuminate\Http\Response
   */
  public function edit(Composer $composer)
  {
    //
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Composer  $composer
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Composer $composer)
  {
    //
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Composer  $composer
   * @return \Illuminate\Http\Response
   */
  public function destroy(Composer $composer)
  {
    //
  }
}

resources/views/composer/_form.blade.php
@if($errors->any())
  <div class="alert alert-danger">
    @foreach ($errors->all() as $error)
      <div>{!! $error !!}</div>
    @endforeach
  </div>
@endif


<form
  data-controller="form"
  data-action="submit->form#submit"
  data-form-action="{!! $action !!}"
  data-form-method="post"
  data-form-redirect="{!! $redirect !!}"
  enctype="multipart/form-data"
>
  @csrf

  @if($composer['id'] != NULL)
    @method('PATCH')
    <input type="hidden" name="id" value="{!! $composer['id'] !!}">
  @endif 

  <div class="row my-padding-bottom-19">
    <div class="col-md-3 col-lg-4 my-padding-bottom-8">
      <label for="fullname">Fullname:<label>
    </div>

    <div class="col-md-9 col-lg-8 my-padding-bottom-8">
      <input
        id="fullname"
        type="text"
        class="form-control"
        name="fullname"
        
        value="{!! 
                old (
                  'fullname',
                  isset($composer) ? $composer['fullname'] : NULL
                )
          !!}"
      >
    </div>
  </div>


  <div class="row my-padding-bottom-19">
    <div class="col-md-3 col-lg-4 my-padding-bottom-8">
      <label for="country-id">Nationality:<label>
    </div>

    <div class="col-md-9 col-lg-8 my-padding-bottom-8">
      <select name="country_id" class="form-control" id="country-id">

        @foreach ($countries as $country)
          <option
            value="{!! $country['id'] !!}"
            {!!
                old (
                  'country_id',
                  isset($composer) && $composer['country_id'] ==
                    $country['id'] ? 'selected' : NULL 
                )
            !!}
          >
            {!! $country['label'] !!}
          </option>
        @endforeach

      </select>
    </div>
  </div>


  <!-- button Save -->

  <div class="row">
    <div class="col-md-3 col-lg-4"></div>

    <div class="col-md-9 col-lg-8">
      <button
        type="submit"
        class="
            btn
            btn-sm
            btn-success
            my-margin-bottom-8
            my-button-form-submit
          "
      >
        <i class="fas fa-check-circle"></i>
        <span>Save</span>
      </button>
    </div>
  </div>

</form>

resources/views/composer/create.blade.php
@extends('_layouts.app')

@section('header')

  <h1 class="text-center">
    Add a new composer
  </h1>

@endsection


@section('content')

  @include(
    'composer/_form',
    
    [
      'errors'    =>  $errors,
      'action'    =>  URL::action('ComposerController@store'),
      'redirect'  =>  URL::action('ComposerController@index'),
      'composer'  =>  $composer
    ]
  )

@endsection

resources/views/composer/index.blade.php
@extends('_layouts.app')

@section('header')

  <h1 class="text-center">
    Composers
  </h1>

  <div
    class="d-flex flex-wrap justify-content-center"
    id="my-composers-action-buttons"
  >
    <a
      href="{!! route('composers.create') !!}"
      class="btn btn-sm btn-outline-success my-margin-4"
    >
      <i class="fas fa-feather-alt my-margin-right-12"></i>
      <span>Add a new composer</span>
    </a>

    <a
      href="{!! route('masterpieces.create') !!}"
      class="btn btn-sm btn-outline-success my-margin-4"
    >
      <i class="fas fa-music my-margin-right-12"></i>
      <span>Add a new masterpiece</span>
    </a>
  </div>

@endsection


@section('content')

  <div
    class="my-margin-bottom-19 my-frame d-none"
    id="my-composer-detail"
  >
  </div>

  <div class="row">

    @foreach($composers as $composer)

      <div class="col-lg-6 col-xl-4 my-padding-bottom-19 my-composer">
        <div class="my-frame">
          <div class="my-padding-bottom-12">
            <span class="h4 font-weight-bold">
              {!! $composer["fullname"] !!}
            </span>
          </div>
          
          <div class="d-flex flex-wrap">

            <div
              class="my-padding-right-8 my-padding-bottom-8"
              data-controller="composer"
              data-composer-url="{!! route('composers.show', $composer["id"]) !!}"
            >
              <button
                class="btn btn-sm btn-outline-dark"
                data-action="click->composer#show"
              >
                <i class="fas fa-eye my-margin-right-12"></i>
                <span>Detail</span>
              </button>
            </div>
            
            <div class="my-padding-right-8 my-padding-bottom-8">
              <a
                href="{!! route('composers.edit', $composer["id"]) !!}" 
                class="btn btn-sm btn-outline-primary"
              >
                <i class="far fa-edit my-margin-right-12"></i>
                <span>Edit</span>
              </a>
            </div>

            <div class="my-padding-bottom-8">
              <button
                class="btn btn-sm btn-danger my-composer-delete"
                data-token="{!! csrf_token() !!}"
                data-url="
                  {!! route('composers.destroy', $composer['id']) !!}
                "
              >
                <i class="far fa-trash-alt my-margin-right-12"></i>
                <span>Delete</span>
              </button>
            </div>

          </div>
        </div>
      </div>

    @endforeach

  </div>

@endsection

resources/views/composer/index_old.blade.php
@extends('_layouts.app')

@section('header')

  <h1 class="text-center">
    Composers
  </h1>

  <div
    class="d-flex flex-wrap justify-content-center"
    id="my-composers-action-buttons"
  >
    <a
      href="{!! route('composers.create') !!}"
      class="btn btn-sm btn-outline-success my-margin-4"
    >
      <i class="fas fa-feather-alt my-margin-right-12"></i>
      <span>Add a new composer</span>
    </a>

    <a
      href="{!! route('masterpieces.create') !!}"
      class="btn btn-sm btn-outline-success my-margin-4"
    >
      <i class="fas fa-music my-margin-right-12"></i>
      <span>Add a new masterpiece</span>
    </a>
  </div>

@endsection


@section('content')

  <div
    class="my-margin-bottom-19 my-frame d-none"
    id="my-composer-detail"
  >
  </div>

  <div class="row">

    @foreach($composers as $composer)

      <div class="col-lg-6 col-xl-4 my-padding-bottom-19 my-composer">
        <div class="my-frame">
          <div class="my-padding-bottom-12">
            <span class="h4 font-weight-bold">
              {!! $composer["fullname"] !!}
            </span>
          </div>
          
          <div class="d-flex flex-wrap">

            <div class="my-padding-right-8 my-padding-bottom-8">
              <a
                href="{!! route('composers.show', $composer["id"]) !!}"
                class="btn btn-sm btn-outline-dark"
              >
                <i class="fas fa-eye my-margin-right-12"></i>
                <span>Detail</span>
              </a>
            </div>

            
            <div class="my-padding-right-8 my-padding-bottom-8">
              <a
                href="{!! route('composers.edit', $composer["id"]) !!}" 
                class="btn btn-sm btn-outline-primary"
              >
                <i class="far fa-edit my-margin-right-12"></i>
                <span>Edit</span>
              </a>
            </div>

            <div class="my-padding-bottom-8">
              <button
                class="btn btn-sm btn-danger my-composer-delete"
                data-token="{!! csrf_token() !!}"
                data-url="
                  {!! route('composers.destroy', $composer['id']) !!}
                "
              >
                <i class="far fa-trash-alt my-margin-right-12"></i>
                <span>Delete</span>
              </button>
            </div>

          </div>
        </div>
      </div>

    @endforeach

  </div>

@endsection

resources/views/composer/show.blade.php
@extends('_layouts.none')

@section('content')

  <h3 class="text-center">
    {!! $composer->fullname !!}
  </h3>

  <h4 class="text-center">
    {!! $composer->country_label !!}
  </h4>

  <div class="my-padding-4 text-center">
    <button
      class="btn btn-sm btn-outline-dark"
      data-controller="composer"
      data-action="composer#hide"
    >
      <i class="fas fa-eye-slash my-margin-right-12"></i>
      <span>Hide</span>
    </button>
  </div>


  <div class="row" data-controller="youtube">

    @foreach($masterpieces as $masterpiece)

      <div
        class="
            col-lg-6
            col-xl-4
            text-center
            my-padding-bottom-19
            my-masterpiece
          "
      >
        <div class="bg-danger text-light my-padding-19">
          <div class="my-padding-bottom-12">
            <span class="h4 font-weight-bold">
              {!! $masterpiece["name"] !!}
            </span>
          </div>

          <iframe
            src="{!! $masterpiece["url"] !!}"
            frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
            data-action="mouseenter->youtube#stopAll"
          ></iframe>

        </div>
      </div>

    @endforeach

  </div>

@endsection

resources/views/composer/show_old.blade.php
@extends('_layouts.app')

@section('header')

  <h3 class="text-center">
    {!! $composer->fullname !!}
  </h3>

  <h4 class="text-center">
    {!! $composer->country_label !!}
  </h4>

@endsection


@section('content')

  <div class="row">

    @foreach($masterpieces as $masterpiece)

      <div
        class="
            col-lg-6
            col-xl-4
            text-center
            my-padding-bottom-19
            my-masterpiece
          "
      >
        <div class="bg-danger text-light my-padding-19">
          <div class="my-padding-bottom-12">
            <span class="h4 font-weight-bold">
              {!! $masterpiece["name"] !!}
            </span>
          </div>

          <iframe
            src="{!! $masterpiece["url"] !!}"
            frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
          ></iframe>

        </div>
      </div>

    @endforeach

  </div>

@endsection